spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.110.201:3306/test01
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: 
    suffix:     